apiVersion: v1
kind: Service
metadata:
  name: node-chat-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: node-chat-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
